# PURL configuration for http://purl.obolibrary.org/obo/trans

idspace: TRANS
base_url: /obo/trans

base_redirect: https://github.com/DiseaseOntology/PathogenTransmissionOntology/tree/main/src/ontology

products:
- trans.owl: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/main/src/ontology/trans.owl
- trans.obo: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/main/src/ontology/trans.obo

term_browser: ols
example_terms:
- TRANS_0000000

- regex: ^/obo/trans/releases/([^\s/]+)/(\S+)$
  replacement: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/v$1/src/ontology/$2
  tests:
  - from: /releases/2022-10-10/trans.owl
    to: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/v2022-10-10/src/ontology/trans.owl
  - from: /releases/2022-10-10/trans.obo
    to: https://raw.githubusercontent.com/DiseaseOntology/SymptomOntology/v2022-10-10/src/ontology/trans.obo
